// <auto-generated />
using Anti_Dox.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Anti_Dox.Migrations
{
    [DbContext(typeof(CsharpiEntities))]
    [Migration("20210218093113_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Anti_Dox.Database.PrefixList", b =>
                {
                    b.Property<long>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<char>("Prefix")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerName")
                        .HasColumnType("TEXT");

                    b.Property<long>("SetById")
                        .HasColumnType("INTEGER");

                    b.HasKey("ServerId");

                    b.ToTable("PrefixList");
                });

            modelBuilder.Entity("Anti_Dox.Database.Settings", b =>
                {
                    b.Property<long>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Discordlogs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("LogsChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerName")
                        .HasColumnType("TEXT");

                    b.Property<long>("SetById")
                        .HasColumnType("INTEGER");

                    b.Property<int>("punishment")
                        .HasColumnType("INTEGER");

                    b.HasKey("ServerId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Anti_Dox.Database.logs", b =>
                {
                    b.Property<double>("GlobalCase")
                        .HasColumnType("REAL");

                    b.Property<string>("IpposterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MesasageContainingIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Punishment")
                        .HasColumnType("TEXT");

                    b.Property<double>("ServerCase")
                        .HasColumnType("REAL");

                    b.Property<long>("ServerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("GlobalCase");

                    b.ToTable("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
